clientes/urls.py
from django.urls import path
from .views import NuevoClienteCreateView, ClientesList110Json

from django.contrib.auth.views import LoginView, LogoutView


urlpatterns = [
   path('cliente/nuevo', NuevoClienteCreateView.as_view(), name='nuevo_cliente'),
   path('clientes_data_110/', ClientesList110Json.as_view(), name="listar_clientes"),#ajax
   path('', LoginView.as_view(template_name='accounts/login.html'), name='login'),
   path('logoutsesion/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
 
]

gescartera_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prestamos.urls')),
    path('', include('clientes.urls')),
    path('', include('reportes.urls')),
]

prestamos/urls.py

from django.urls import path
from .views import home, nuevo_Prestamo,autocompleteModel,traerDatosdeCliente, nuevo_Abono, UsersList110Json,PrestamosList110Json,AbonosList110Json,registrar_abono,nuevo_union_cuentas,PrestamosTodosList110Json,borrar_Prestamo,borrar_Abono,mostrar_estado_cuenta,descuento_Prestamo,registrar_descuento,DescuentosList110Json,borrar_Descuento

urlpatterns = [
   path('inicio/', home, name='home'),
   path('prestamo/nuevo/', nuevo_Prestamo, name='nuevoPrestamo'), #ajax
   path('prestamo/descuento/', descuento_Prestamo, name='descuentoPrestamo'), #ajax copia de abono nuevo
   path('prestamo/borrar/', borrar_Prestamo, name='borrarPrestamo'), #ajax
   path('abono/borrar/', borrar_Abono, name='borrarAbono'), #ajax
   path('descuento/borrar/', borrar_Descuento, name='borrarDescuento'), #ajax
   path('abono/nuevo', nuevo_Abono, name='nuevoAbono'),
   path('unioncuentas/nuevo/', nuevo_union_cuentas, name='nuevo_union_cuen'),
   path('ajax_calls/search/', autocompleteModel, name='search'),
   path('ajax_calls/traerDatosdeCliente/', traerDatosdeCliente, name='traerDatosdeCliente'),#ajax
   path('ajax_calls/registrarAbono/', registrar_abono, name='registrar_abono'),#ajax
   path('ajax_calls/registrarDescuento/', registrar_descuento, name='registrar_descuento'),#ajax
   path('users_data_110/', UsersList110Json.as_view(), name="UsersList110Json"),#ajax
   path('prestamos_data_110/', PrestamosList110Json.as_view(), name="PrestamosList110Json"),#ajax
   path('abonos_data_110/', AbonosList110Json.as_view(), name="AbonosList110Json"),#ajax
   path('descuentos_data_110/', DescuentosList110Json.as_view(), name="DescuentosList110Json"),#ajax
   path('prestamos_todos_110/', PrestamosTodosList110Json.as_view(), name="listar_prestamos_todos"),#ajax
   path('prestamo/estadocuenta/', mostrar_estado_cuenta, name="mostrar_estado_cuenta_cliente"),
]

prestamos/models.py
from django.db import models
from clientes.models import Cliente
#from django.contrib.auth.models import User

#from datetime import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
#from users.models import Cobrador


class Interes(models.Model):
	porcentaje = models.FloatField()
	descripcion = models.TextField(max_length=140)

	def __str__(self):
		return str(self.porcentaje)

class TiposPrestamo(models.Model):
	tipo = models.CharField(max_length=30)

	def __str__(self):
		return self.tipo



class EstadoAbono(models.Model):
	estado = models.CharField(max_length=30)

	def __str__(self):
		return self.estado

class EstadoPrestamo(models.Model):
	estado = models.CharField(max_length=40)

	def __str__(self):
		return self.estado

		
class Prestamo(models.Model):
	
    
	cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
	fecha_prestamo = models.DateField(default=timezone.now)
	capital_prestado = models.FloatField()
	meses_plazo = models.IntegerField(verbose_name='Tiempo plazo')
	porcentaje_aplicado = models.ForeignKey(Interes, on_delete=models.CASCADE)
	valor_interes = models.FloatField(null=True)
	saldo_capital = models.FloatField(null=True)
	saldo_interes = models.FloatField(null=True)
	tipo_prestamo = models.ForeignKey(TiposPrestamo, on_delete=models.CASCADE)
	fecha_registro = models.DateTimeField(default=timezone.now)
	prestamo_nuevo = models.ForeignKey('Prestamo', on_delete=models.CASCADE, blank= True, null=True)
	estado = models.ForeignKey('EstadoPrestamo', on_delete = models.CASCADE, blank= True, default=1)
	#estado = models.IntegerField(choices=ESTADOS, default=PENDIENTE, blank= True)
	observaciones = models.TextField(max_length=150,blank=True)
	cobrador = models.ForeignKey(get_user_model(), on_delete= models.CASCADE, default='')

	def __str__(self):
		return "{0},{1},{2}".format(self.fecha_prestamo, self.cliente, self.capital_prestado)

class Abono(models.Model):
	prestamo = models.ForeignKey(Prestamo,on_delete=models.CASCADE)
	fecha_abono = models.DateField(default=timezone.now)
	valor_abono_capital = models.FloatField()
	valor_abono_interes = models.FloatField()
	observaciones = models.TextField(max_length=100,blank=True,null=True)
	fecha_registro = models.DateTimeField(default=timezone.now)
	estado = models.ForeignKey(EstadoAbono, on_delete = models.CASCADE, blank= True, null=True)
	cobrador = models.ForeignKey(get_user_model(), on_delete= models.CASCADE, default='')

	def __str__(self):
		return "{0},{1}".format(self.fecha_abono, self.valor_abono_capital)


class Descuento(models.Model):
	prestamo = models.ForeignKey(Prestamo,on_delete=models.CASCADE)
	fecha_descuento = models.DateField(default=timezone.now)
	valor_descuento = models.FloatField(default=0, null=False)
	fecha_registro = models.DateTimeField(default=timezone.now)
	descontadopor = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
	
	def __str__(self):
		return "descuento: {0}, {1}".format(self.fecha_descuento, self.valor_descuento)

class UnionCuentas(models.Model):
	fecha_union = models.DateField(default=timezone.now)
	fecha_registro = models.DateTimeField(default=timezone.now)
	capital_total = models.FloatField()
	valor_abono_capital_total = models.FloatField()
	valor_abono_interes_total = models.FloatField()
	saldo = models.FloatField() #este saldo es saldo al capital
	#usuario = models.ForeignKey(User, on_delete= models.CASCADE)

	def __str__(self):
		return "{},{}".format(self.fecha_union,self.saldo)
	
class UnionCuentasDetalle(models.Model):
	union_cuentas = models.ForeignKey(UnionCuentas, on_delete=models.CASCADE)
	prestamo = models.ForeignKey(Prestamo, on_delete=models.CASCADE)
	

	def __str__(self):
		return "detalle id: {0}, maestro id: {1}, prestamo id: {2}".format(self.id, self.union_cuentas, self.prestamo.id)

class PlanFinanciero(models.Model):
	fecha_registro = models.DateTimeField(default=timezone.now)
	#usuario = models.ForeignKey(User, on_delete= models.CASCADE)
	cliente = models.ForeignKey(Cliente, on_delete= models.CASCADE)
	prestamo = models.ForeignKey(Prestamo, on_delete= models.CASCADE)

	def __str__(self):
		return "{}-{}-{}".format(self.usuario, self.cliente, self.prestamo)

class PlanFinancieroDetalle(models.Model):
	plan_financiero = models.ForeignKey(PlanFinanciero, on_delete= models.CASCADE)
	fecha_abono = models.DateField(default=timezone.now)
	valor_capital = models.FloatField()
	valor_interes = models.FloatField()
	concepto = models.CharField(max_length=80)

	def __str__(self):
		return "{}-{}-{}-{}".format(self.plan_financiero, self.valor_capital, self.valor_interes, self.concepto)







prestamos/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
#from django.contrib.auth.models import User
import json

from .forms import PrestamoForm, AbonoForm, DescuentoForm
from clientes.models import Cliente
from .models import ( Prestamo,TiposPrestamo,Interes,Abono,EstadoAbono,
	PlanFinanciero, PlanFinancieroDetalle,UnionCuentas,UnionCuentasDetalle, Descuento
	)

from django.contrib.auth import get_user_model

from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.generic import TemplateView
from django.utils.safestring import mark_safe
from django.db.models import Q,F,Sum, Value as V, OuterRef, Subquery, ExpressionWrapper, FloatField
from django.db.models.functions import Coalesce
from django.utils.html import escape

import datetime
from datetime import timedelta
from django.utils import timezone

import calendar #realmente usando

from django.contrib.auth.decorators import login_required

@login_required
def nuevo_union_cuentas(request):
	if request.method=='GET':
		form = PrestamoForm()
		return render(request,'prestamos/unioncuentas.html',{'form': form})
	else:
		form = PrestamoForm(request.POST)

		if form.is_valid():
			prestamo_object = Prestamo()
			
			form.save(commit=False)
			id_client = request.POST['id_cliente']
			id_prestamus = request.POST['id_prestamo']
			#print (id_client)
			form.cliente = Cliente.objects.get(id=id_client)
			prestamo_obj_viejo = Prestamo.objects.get(id=id_prestamus)
			
			prestamo_object.cliente= Cliente.objects.get(id=id_client)
			cobradore = get_user_model()
			prestamo_object.cobrador= cobradore#request.user
			prestamo_object.fecha_prestamo = request.POST['fecha_prestamo']
			prestamo_object.capital_prestado = float(request.POST['capital_prestado'])
			prestamo_object.tipo_prestamo = TiposPrestamo.objects.get(id=request.POST['tipo_prestamo'])
			prestamo_object.meses_plazo = int(request.POST['meses_plazo'])
			prestamo_object.porcentaje_aplicado = Interes.objects.get(id=request.POST['porcentaje_aplicado'])
			prestamo_object.observaciones = request.POST['observaciones']
			prestamo_object.prestamo_nuevo = Prestamo.objects.get(id=id_prestamus)
			prestamo_object.estado = 3 #fusionado
						
			prestamo_object.save()

			form.usuario = cobradore#request.user

			#guardar union cuentas maestro y detalle
			unionc = UnionCuentas()
			unionc.capital_total = prestamo_object.capital_prestado + prestamo_obj_viejo.capital_prestado
			Tabono_a_capital = Abono.objects.filter(prestamo=prestamo_object.id).aggregate(tot_valo_abo=Coalesce(Sum('valor_abono_capital'), V(0))).get('tot_valo_abo') #Abono.objects.filter(prestamo=prestamo_object.id).aggregate(tota_abono_capital=Coalesce(Sum('valor_abono_capital'), V(0))).get('tota_abono_capital')
			Tabono_a_capital_2 = Abono.objects.filter(prestamo=prestamo_obj_viejo.id).aggregate(tot_valo_abo_e=Coalesce(Sum('valor_abono_capital'), V(0))).get('tot_valo_abo_e')#Abono.objects.filter(prestamo=prestamo_obj_viejo.id).aggregate(tota_abono_interes=Coalesce(Sum('valor_abono_capital'), V(0)).get('tota_abono_interes'))

			#print ('Tabono_a_capital: {}'.format(Tabono_a_capital))
			#print ('Tabono_interes: {}'.format(Tabono_a_capital_2))

			unionc.valor_abono_capital_total = Tabono_a_capital + Tabono_a_capital_2
			unionc.valor_abono_interes_total = Abono.objects.filter(prestamo=prestamo_object.id).aggregate(tot_valo_abo=Coalesce(Sum('valor_abono_interes'), V(0))).get('tot_valo_abo')  + Abono.objects.filter(prestamo=prestamo_obj_viejo.id).aggregate(tot_valo_abo_e=Coalesce(Sum('valor_abono_interes'), V(0))).get('tot_valo_abo_e')#float(Abono.objects.filter(prestamo=prestamo_object.id).aggregate(Coalesce(Sum('valor_abono_interes'), V(0)).get('valor_abono_interes__sum'))) + float(Abono.objects.filter(prestamo=prestamo_obj_viejo.id).aggregate(Coalesce(Sum('valor_abono_interes'), V(0)).get('valor_abono_interes__sum')))
			unionc.saldo = unionc.capital_total - unionc.valor_abono_capital_total
			#unionc.usuario = User.objects.first()

			unionc.save()

			unionc_detalle_1 = UnionCuentasDetalle()
			unionc_detalle_1.union_cuentas = unionc
			unionc_detalle_1.prestamo = prestamo_object
			unionc_detalle_1.save()

			unionc_detalle_2 = UnionCuentasDetalle()
			unionc_detalle_2.union_cuentas = unionc
			unionc_detalle_2.prestamo = prestamo_obj_viejo
			unionc_detalle_2.save()


			#form.save()
			#print ("en el post de creacion de union cuentas VALID")

			data = 'fail'

			data = {
    		'id': unionc.id,
    		
    		}

			return JsonResponse(data, safe=False)


			#form.cliente = 
			#form = PrestamoForm()
			#return render(request,'prestamos/unioncuentas.html',{'form': form})
		else:

			return render(request,'prestamos/unioncuentas.html',{'form': form})

def monthdelta(date, delta):
    m, y = (date.month+delta) % 12, date.year + ((date.month)+delta-1) // 12
    if not m: m = 12
    d = min(date.day, calendar.monthrange(y, m)[1])
    return date.replace(day=d,month=m, year=y)





class UsersList110(TemplateView):
    template_name = 'prestamos/abonosnew.html'


class AbonosList110Json(BaseDatatableView):
	model = Abono
	columns = ['id','fecha_abono', 'valor_abono_capital',  'valor_abono_interes','accion']

	def filter_queryset(self, qs):
		search = self.request.GET.get(u'search[value]', None)
		if search:
			qs = qs.filter(Q(id__istartswith=search) | Q(fecha_abono__istartswith=search) | Q(valor_abono_capital__istartswith=search))

		#print (qs)

		return qs

	def render_column(self, row, column):
		if column == 'accion':
			return mark_safe('<a href="#" >Consulta</a>') #135X140 #<a href="{0}"><img src="{0}" width="100" height="110" alt="Sin foto"></a>
		else:
			return super(AbonosList110Json, self).render_column(row, column)


	def get_initial_queryset(self):
		id_prest = self.request.GET.get('id_prestamo', None)
		return Abono.objects.values('id','fecha_abono','valor_abono_capital','valor_abono_interes').filter(prestamo__id=id_prest).order_by('fecha_abono')

	def prepare_results(self, qs):
		json_data = []
		for item in qs:
			json_data.append([item["id"],item["fecha_abono"].strftime("%d-%m-%Y"),escape('{:,}'.format(item["valor_abono_capital"])),escape('{:,}'.format(item["valor_abono_interes"])), mark_safe('<a href="#" class="btn btn-outline-warning btn-sm" role="button">Editar</a><button type="submit" onclick="borrarAbono(this);" class="btn btn-outline-danger btn-sm">Borrar</button>') ])

		return json_data


class DescuentosList110Json(BaseDatatableView):
	model = Descuento
	columns = ['id','fecha_descuento', 'valor_descuento','accion']

	def filter_queryset(self, qs):
		search = self.request.GET.get(u'search[value]', None)
		if search:
			qs = qs.filter(Q(id__istartswith=search) | Q(fecha_descuento__istartswith=search) | Q(valor_descuento__istartswith=search))

		#print (qs)

		return qs

	def render_column(self, row, column):
		if column == 'accion':
			return mark_safe('<a href="#" >Consulta</a>') #135X140 #<a href="{0}"><img src="{0}" width="100" height="110" alt="Sin foto"></a>
		else:
			return super(DescuentosList110Json, self).render_column(row, column)


	def get_initial_queryset(self):
		id_prest = self.request.GET.get('id_prestamo', None)
		return Descuento.objects.values('id','fecha_descuento','valor_descuento').filter(prestamo__id=id_prest).order_by('fecha_descuento')

	def prepare_results(self, qs):
		json_data = []
		for item in qs:
			json_data.append([item["id"],item["fecha_descuento"].strftime("%d-%m-%Y"),escape('{:,}'.format(item["valor_descuento"])), mark_safe('<a href="#" class="btn btn-outline-warning btn-sm" role="button">Editar</a><button type="submit" onclick="borrarDescuento(this);" class="btn btn-outline-danger btn-sm">Borrar</button>') ])

		return json_data


class PrestamosTodosList110Json(BaseDatatableView):
	model = Prestamo
	columns = ['id','fecha_prestamo', 'cliente', 'cliente',  'capital_prestado','tipo_prestamo','accion']
	#order_columns = ['capital_prestado']

	#def render_column(self, row, column):
		#if column == 'accion':
			#return mark_safe('<a href="#" >Consulta</a>') #135X140 #<a href="{0}"><img src="{0}" width="100" height="110" alt="Sin foto"></a>
		#else:
			#return super(UsersList110Json, self).render_column(row, column)

	def filter_queryset(self, qs):
		search = self.request.GET.get(u'search[value]', None)
		if search:
			qs = qs.filter(Q(id__istartswith=search) | Q(fecha_prestamo__istartswith=search) | Q(capital_prestado__istartswith=search) | Q(cliente__nombres__istartswith=search) | Q(cliente__apellidos__istartswith=search))

		#print (qs)

		return qs

	def get_initial_queryset(self):
		return Prestamo.objects.values('id','fecha_prestamo','cliente__nombres','cliente__apellidos','capital_prestado','tipo_prestamo__tipo').filter(estado=1).order_by('-fecha_prestamo')

	def prepare_results(self, qs):
		json_data = []
		for item in qs:
			json_data.append([item["id"],item["fecha_prestamo"].strftime("%d-%m-%Y"),item["cliente__nombres"],item["cliente__apellidos"],escape('{:,}'.format(item["capital_prestado"])),item["tipo_prestamo__tipo"], mark_safe('<button id = "btEditarPrestamo"  type="submit" class="btn btn-outline-warning btn-sm">Editar</button><button type="submit" onclick="borrarPrestamo(this);" class="btn btn-outline-danger btn-sm">Borrar</button>') ])

		return json_data



class PrestamosList110Json(BaseDatatableView):
	
	#model = Prestamo
	columns = ['id','capital_prestado', 'fecha_prestamo',  'porcentaje_aplicado__porcentaje','abonos_capital','saldo_capital','accion']
	#order_columns = ['capital_prestado']

	#def render_column(self, row, column):
		#if column == 'accion':

prestamos/templates/prestamos/estado_cuenta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Estado de cuenta</title>
</head>
<body>
    <h1>Aquí va el estado de cuenta del prestamo {{ id_prestam }}</h1>
    
</body>
</html>

prestamos/templates/prestamos/unioncuentas.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load i18n staticfiles %}
{% block extra_head %}
	<link rel="stylesheet" href="{% static 'css/misestilos.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.css' %}">
    
   
{% endblock %}

{%block opcionactiva %}Unir cuentas{% endblock %}

{% block content %}
		<div class="row">
			<div class="col-md-12">
						
			</div>
	
		</div>


		<div class="row" id="divforms">
			<div class="col-md-12" >
				<form id="formsearch" method="POST" onsubmit="return false;">
					{% csrf_token %}
					<label><strong>Digite nombre del cliente para realizar busqueda</strong></label>
					<input type="text" class="form-control txtSearch" id="txtSearch" name="txtSearch">
			   </form>

			  				 
							   <div id="datoscliente">
					
							   </div>
		
				<div class="card">
				   <div class="card-header text-center" style="background: #d5b8ff; color: white;">
					 <strong> Listado de prestamos del cliente  </strong>
				   </div>
				   <div class="card-body">
					 
					   <div class="table-responsive">
						   <table id="tablaPrestamos" class="datatable" style="width:100%"> 
							   <thead>
								   <th>{% trans "id" %}</th>
								   <th>{% trans "Capital prestado" %}</th>
								   <th>{% trans "Fecha prestamo" %}</th>
								   <th>{% trans "Porcentaje" %}</th>
								   <th>{% trans "Abonos a capital" %}</th>
								   <th>{% trans "Saldo capital" %}</th>
								   <th>{% trans "Acción" %}</th>
   							   </thead>
							   <tbody>
							   </tbody>
						   </table>
   
					   </div> 
					 
				   </div>
				 </div>

			
			    
			</div>

		</div>

		</br>
		<div>
			<div class="col-md-12" >
					<div class="card">
							<div class="card-header text-center">
							   Registrar prestamo para unión de cuentas
							</div>
							<div class="card-body">
								<form method='POST' novalidate>
									{% csrf_token %}
									{% include 'form.html' %}
		   
									<input type="hidden" id="cliid" name="cliid" value="">
									<input type="hidden" id="id_prestam" name="id_prestam" value="">
		   							<button id="guardar" type="submit" class="btn btn-success">Guardar</button>
		   
							  	 </form>
						  
							</div>
							<div class="card-footer">
								<div id="mensajes">
					 	
								</div>
							</div>
					</div>
			</div>
		</div>
		
{% endblock %}

{% block js %}
	
 <script type="text/javascript" charset="utf8" src="{% static 'js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'js/ddv_example_1_10.js' %}"></script>
    <script type="text/javascript">

    	
    	
     /*  USERS_LIST_JSON_URL = '{% url "UsersList110Json" %}';*/
      
       var dt_language = {
            "emptyTable":     "{% trans 'No existen registros' %}",
            "info":           "{% trans 'Mostrar _START_ a _END_ de _TOTAL_ registros' %}",
            "infoEmpty":      "{% trans 'Mostrando 0 a 0 of 0 registros' %}",
            "infoFiltered":   "{% trans '(filtrado de _MAX_ registros totales)' %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans 'Show _MENU_ entries' %}",
            "loadingRecords": "{% trans 'Cargando...' %}",
            "processing":     "{% trans 'Procesando...' %}",
           /* "search":         "{% trans 'Buscar:' %}",*/
            "zeroRecords":    "{% trans 'No existen registros' %}",
            /*"paginate": {
                "first":      "{% trans 'Primero' %}",
                "last":       "{% trans 'Ultimo' %}",
                "next":       "{% trans 'Siguiente' %}",
                "previous":   "{% trans 'Anterior' %}"
            },*/
            "aria": {
                "sortAscending":  "{% trans ': activate to sort column ascending' %}",
                "sortDescending": "{% trans ': activate to sort column descending' %}"
            }
        }

    </script>


   <!-- otros jquery -->
	

	<script>
		

        $(document).ready(function(){ 
            $("#txtSearch").autocomplete({
                source: "/ajax_calls/search/",
                minLength: 2,
                open: function(){
                    setTimeout(function () {
                        $('.ui-autocomplete').css('z-index', 99);
                    }, 0);
                }
              });
        });

       $(document).ready(function(){ 
        $( "#txtSearch" ).change(function() {
  			//alert( "Handler for .change() called." );
  			//e.preventDefault();
  			var id_delcliente = 0;
  			var nombrecompleto = $(this).val().trim();

  			console.log("en el evento change nombrecompleto es "+ nombrecompleto);
  			if (nombrecompleto!=''){

  					nombrecompletosplitted = nombrecompleto.split(',');

					var nombress = nombrecompletosplitted[0].trim();
			  		var apellidoss = nombrecompletosplitted[1].trim();
			  							
			  		  $.ajax({
				        url: '/ajax_calls/traerDatosdeCliente/',
				        data: {
				          'nombres': nombress,
				          'apellidos': apellidoss,

				        },
					        dataType: 'json',
					        success: function (data) {
					         
					          $('#datoscliente').html($('<label><strong>Nombres</strong>: '+ data.nombres +'</label></br><label><strong>Apellidos</strong>: '+ data.apellidos +'</label></br><label> <strong>Dirección</strong>: '+ data.direccion +'</label>'));
					          
					          $("#cliid").val(data.id);
					          id_delcliente = data.id;
					         // alert("id_delcliente 1 ajax : "+id_delcliente);
					           if ($("#cliid").val()==''){
					           		alert("por favor seleccione un cliente");
					           }
	           

					           /****** poblar la datatable *******/
					           	//poblarDatatable();
					           	
					           	//alert($("#cliid").val());
					        	/* fin de poblar la datatable*/
					        },
					        error: function () {
					            $('#datoscliente').html($('<label>No existe el cliente consultado</label>'));
					        }

					        
					      }).done(function(data) {

					      	USERS_LIST_JSON_URL = '{% url "PrestamosList110Json" %}';
					      	     cargarPrestamos(id_delcliente);

						      });

				  			}else{
				  				alert('por favor digite un nombre de cliente a buscar.');
				  				return;
				  			}

				  			


		});
		  });

		$( "#txtSearch" ).keyup(function() {
  			$(this).val($(this).val().toUpperCase());
		});

    $("#tablaPrestamos").on("click", "tr", function() {          
   			if (id_prest!=0 || id_prest != undefined){
				console.log($(this).children(":first").text());
				var id_prest = $(this).children(":first").text();
				ABONOS_LIST_JSON_URL = '{% url "AbonosList110Json" %}';
								$("#id_prestam").val(id_prest);//agregar id_prestamo a campo oculto parausarlo en el registor el abono
								//cargarAbonos(id_prest);
			}
});



		$(document).ready(function(){ 
        $( "#guardar" ).click(function(e) {
			e.preventDefault();

			  console.log("cliente: " + $("#cliid").val());
			  console.log("prestamo id: " + $("#id_prestam").val());

			  if ($("#cliid").val()=='' || typeof $("#cliid").val() === 'undefined'){
					           		alert("por favor consulte un cliente.");
									return ;
					           }
			  			
  			if ($("#id_prestam").val()!='' && typeof $("#id_prestam").val() != 'undefined')
			  {

				console.log("ok el prestamo seleccionado fue: "+ $("#id_prestam").val());
				
				var csrftoken = $("[name=csrfmiddlewaretoken]").val();
				  							
			  		  $.ajax({
						url: '/unioncuentas/nuevo/',
						type: 'POST',
						headers:{
      					  "X-CSRFToken": csrftoken
    					},
				        data: {
							csrfmiddlewaretoken: csrftoken,
						  'id_cliente': $("#cliid").val(),
						  'id_prestamo': $("#id_prestam").val(),
						  'fecha_prestamo': $("#id_fecha_prestamo").val(),
						  'capital_prestado': $("#id_capital_prestado").val(),
						  'tipo_prestamo': $("#id_tipo_prestamo").val(),
				          'meses_plazo': $("#id_meses_plazo").val(),
						  'porcentaje_aplicado': $("#id_porcentaje_aplicado").val(),
						  'observaciones': $("#id_observaciones").val(),
						  
				        },
					        dataType: 'json',
					        success: function (data) {
					         
					          $('#mensajes').html($('<div class="alert alert-success" role="alert"> Unión de cuenta N° '+ data.id +' registrado con éxito</div>'));
					          	//cargarAbonos($("#id_prestam").val());
				              },

					        error: function (xhr, status, error) {
								var errorMessage = xhr.status + ': ' + xhr.statusText
					            $('#mensajes').html($('<div class="alert alert-danger" role="alert"> Error en el registro de la unión de cuentas: '+ errorMessage + ':'+ error +'</div>'));
					        }

					        
					      });

				}else{
				  		alert('por favor seleccione un prestamo, para registrar la union de cuentas.');
				  		return;
				  	}

		});
		  });




 
	</script>
{% endblock %}